updates and release

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5,11 +5,18 @@
 #
 #
 
+#Get the number of CPUs
+cpucores=`getconf _NPROCESSORS_ONLN`
+
 #VARIABLES
+MAKE=${MAKE:-make -j $(cpucores) -l $((cpucores + 1))}
 BASEDIR=$(pwd)
 TMPDIR=$BASEDIR/_$$
 BUILD_DEPENDENCIES='true'
 err=0
+
+CUDAVALUE="OFF"
+MPIVALUE="OFF"
 
 
 mkdir -p $TMPDIR
@@ -24,6 +31,10 @@ print_usage() {
 while [ -n "$1"  ]
 do
     case "$1" in
+        --enable-cuda)
+            CUDAVALUE="ON"
+            shift
+            ;;
         --enable-mpi)
             MPIVALUE="ON"
             shift
@@ -91,12 +102,14 @@ case "$osType" in
     {
         echo "Running on Mac OSX."
         CURRENT_OS="OSX"
+        LIBEXT="dylib"
         export DYLD_LIBRARY_PATH=$PREFIX/lib:$DYLD_LIBRARY_PATH
     } ;;
     "Linux")
     {
         echo "Running on LINUX."
         CURRENT_OS="LINUX"
+        LIBEXT="so"
         export LD_LIBRARY_PATH=$PREFIX/lib:$LD_LIBRARY_PATH
     } ;;
     *)
@@ -117,6 +130,9 @@ export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH
 if [ -n "$MKLROOT" ] && [ -d "$MKLROOT" ]; then
     echo "mkl_dir directory exists!"
     echo "Great... continue set-up"
+    source ${MKLROOT}/bin/mklvars.sh intel64
+    DEFINE_BLAS_LIBS_CMAKE="-DBLAS_LIBRARIES='-L${MKLROOT}/lib -Wl,-rpath,${MKLROOT}/lib -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl'"
+    #DEFINE_BLAS_LIBS_CMAKE="-DBLAS_LIBRARIES='-L${MKLROOT}/lib\ -Wl,-rpath,${MKLROOT}/lib\ -lmkl_intel_lp64\ -lmkl_sequential\ -lmkl_core\ -lpthread\ -lm\ -ldl'"
     XFLAG="-DBLA_VENDOR=Intel"
 else
     echo "MKL not found, trying to compile and use OpenBLAS"
@@ -141,7 +157,8 @@ then
             cd $TMPDIR
             wget https://github.com/xianyi/OpenBLAS/archive/v0.3.3.tar.gz -O - | tar -zx
             cd OpenBLAS-0.3.3
-            make -j  >/dev/null|| make && make install PREFIX=$PREFIX
+            $MAKE -j  >/dev/null|| $MAKE || { echo 'OpenBLAS installation failed' ; exit 1; }
+	    $MAKE install PREFIX=$PREFIX
             export CPATH=$CPATH:$PREFIX/include
         else
             echo "####################"
@@ -167,7 +184,8 @@ else
         wget https://ftp.gnu.org/gnu/gsl/gsl-2.4.tar.gz -O - | tar -zx
         cd gsl-2.4
         ./configure --prefix=$PREFIX
-        make -j || make && make install
+        $MAKE || $MAKE VERBOSE=1 || { echo 'GSL installation failed' ; exit 1; }
+	$MAKE install
     else
         echo "####################"
         echo "gsl NOT FOUND"
@@ -191,7 +209,8 @@ else
         wget http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz -O - | tar -zx
         cd nlopt-2.4.2
         ./configure --enable-shared --without-guile --prefix=$PREFIX
-        make -j || make && make install
+        $MAKE || $MAKE VERBOSE=1 || { echo 'NLOPT installation failed' ; exit 1; }
+        $MAKE install
     else
         echo "####################"
         echo "nlopt NOT FOUND"
@@ -215,7 +234,8 @@ else
         wget https://www.open-mpi.org/software/hwloc/v1.11/downloads/hwloc-1.11.5.tar.gz -O - | tar -zx
         cd hwloc-1.11.5
         ./configure --prefix=$PREFIX
-        make -j || make && make install
+         $MAKE || $MAKE VERBOSE=1 || { echo 'HWLOC installation failed' ; exit 1; }
+	 $MAKE install
     else
         echo "####################"
         echo "hwloc NOT FOUND"
@@ -238,8 +258,13 @@ else
         cd $TMPDIR
         wget http://starpu.gforge.inria.fr/files/starpu-1.2.5/starpu-1.2.5.tar.gz -O - | tar -zx
         cd starpu-1.2.5
-        ./configure --disable-cuda --disable-opencl --prefix=$PREFIX
-        make -j || make && make install
+        if [ "$CUDAVALUE" == "ON" ]; then
+            ./configure --enable-cuda --disable-opencl --prefix=$PREFIX
+        else
+            ./configure --disable-cuda --disable-opencl --prefix=$PREFIX
+        fi
+        $MAKE || $MAKE VERBOSE=1 || { echo 'STARPU installation failed' ; exit 1; }
+        $MAKE install
     else
         echo "####################"
         echo "StarPU NOT FOUND"
@@ -251,7 +276,7 @@ else
 fi
 
 cd $BASEDIR
-
+set -x
 # CHAMELEON
 if pkg-config --exists chameleon
 then
@@ -263,8 +288,10 @@ else
         echo "Building CHAMELEON..."
         cd $BASEDIR/src/hicma/chameleon
         mkdir -p build && cd build
-        cmake .. -DCHAMELEON_USE_MPI=$MPIVALUE -DCHAMELEON_ENABLE_EXAMPLE=OFF -DCHAMELEON_ENABLE_TESTING=OFF -DCHAMELEON_ENABLE_TIMING=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$PREFIX
-        make -j 20 || make VERBOSE=1 && make install
+        rm -rf ./CMake*
+        cmake -DCHAMELEON_USE_MPI=$MPIVALUE -DCHAMELEON_USE_CUDA=$CUDAVALUE -DCHAMELEON_ENABLE_EXAMPLE=OFF -DCHAMELEON_ENABLE_TESTING=OFF -DCHAMELEON_ENABLE_TIMING=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$PREFIX "$DEFINE_BLAS_LIBS_CMAKE" ..
+        $MAKE || $MAKE VERBOSE=1 || { echo 'CHAMELEON installation failed' ; exit 1; }
+        $MAKE install
     else
         echo "####################"
         echo "CHAMELEON NOT FOUND"
@@ -286,8 +313,10 @@ else
         echo "Building STARS-H..."
         cd $BASEDIR/src/stars-h
         mkdir -p build && cd build
-        cmake .. -DCMAKE_C_FLAGS=-fPIC -DEXAMPLES=OFF -DTESTING=OFF -DMPI=$MPIVALUE -DCMAKE_INSTALL_PREFIX=$PREFIX
-        make -j 20 || make VERBOSE=1 && make install
+        rm -rf ./CMake*
+        cmake -DCMAKE_C_FLAGS=-fPIC -DEXAMPLES=OFF -DTESTING=OFF -DMPI=$MPIVALUE -DCMAKE_INSTALL_PREFIX=$PREFIX "$XFLAG" "$DEFINE_BLAS_LIBS_CMAKE" ..
+        $MAKE || $MAKE VERBOSE=1 || { echo 'STARS-H installation failed' ; exit 1; }
+        $MAKE install
     else
         echo "####################"
         echo "starsh NOT FOUND"
@@ -299,7 +328,7 @@ else
 fi
 
 # hicma
-if pkg-config --exists --atleast-version=0.1.1 hicma
+if pkg-config --exists  hicma
 then
     _LOCATION=`pkg-config --variable=prefix hicma`
     echo "hicma FOUND in [$_LOCATION]"
@@ -309,8 +338,10 @@ else
         echo "Building HiCMA..."
         cd $BASEDIR/src/hicma/
         mkdir -p build && cd build
-        cmake .. -DHICMA_USE_MPI=$MPIVALUE -DBUILD_SHARED_LIBS=ON -DHICMA_ENABLE_TESTING=OFF -DHICMA_ENABLE_TIMING=OFF -DCMAKE_INSTALL_PREFIX=$PREFIX
-        make -j 20 || make VERBOSE=1 && make install
+        rm -rf ./CMake*
+        cmake -DHICMA_USE_MPI=$MPIVALUE -DBUILD_SHARED_LIBS=ON -DHICMA_ENABLE_TESTING=OFF -DHICMA_ENABLE_TIMING=OFF -DCMAKE_INSTALL_PREFIX=$PREFIX "$XFLAG" "$DEFINE_BLAS_LIBS_CMAKE" ..
+        $MAKE || $MAKE VERBOSE=1 || { echo 'HICMA installation failed' ; exit 1; }
+        $MAKE install
     else
         echo "####################"
         echo "hicma NOT FOUND"
@@ -324,6 +355,15 @@ fi
 # use rpaths in makefile
 # TODO use a R defined value por PREFIX and have this directly in the Makefile
 
+#Dummy makefile in src to trigger real one from cmake.
+cd $BASEDIR/
+rm -rf ./CMakeFiles ./CMakeCache.txt
+cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_C_FLAGS_RELEASE="-O3 -Ofast" -DBUILD_SHARED_LIBS=ON -DEXAGEOSTAT_EXAMPLES=OFF "$XFLAG" "$DEFINE_BLAS_LIBS_CMAKE" -DEXAGEOSTAT_USE_MPI=$MPIVALUE -DEXAGEOSTAT_USE_HICMA=ON ./src
+cat > src/Makefile << EOF
+.PHONY: all clean
+all:
+	(cd .. && make VERBOSE=1 && cp ./lib*.${LIBEXT} ./src/exageostat.so)
 
+EOF
 
 exit $err
